#!/usr/bin/env bash

APP_NAME=EasyEraserMain
ARCH_MIPS64=mips64
ARCH_X86_64=x86_64
ARCH_AARCH64=aarch64

ARCH=$(uname -m)

# shellcheck disable=SC2046
ROOT_DIR=$(cd $(dirname "$0") && pwd)

if [[ $ARCH =~ $ARCH_X86_64 ]]; then
  "${ROOT_DIR}"/$ARCH_X86_64/$APP_NAME
elif [[ $ARCH =~ $ARCH_AARCH64 ]]; then
  "${ROOT_DIR}"/$ARCH_AARCH64/$APP_NAME
elif [[ $ARCH =~ $ARCH_MIPS64 ]]; then
  "${ROOT_DIR}"/$ARCH_MIPS64/$APP_NAME
else
  echo "ERROR: unsupported arch ${ARCH}!"
fi
