# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EasyEraser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        Dialog.setMinimumSize(QtCore.QSize(800, 400))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1200))
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(670, 20, 80, 32))
        self.search_btn.setDefault(False)
        self.search_btn.setObjectName("search_btn")
        self.file_table = QtWidgets.QTableWidget(Dialog)
        self.file_table.setGeometry(QtCore.QRect(20, 110, 760, 360))
        self.file_table.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(1)
        self.file_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        self.file_lst_label = QtWidgets.QLabel(Dialog)
        self.file_lst_label.setGeometry(QtCore.QRect(20, 70, 60, 28))
        self.file_lst_label.setObjectName("file_lst_label")
        self.dir_text = QtWidgets.QPlainTextEdit(Dialog)
        self.dir_text.setGeometry(QtCore.QRect(100, 20, 280, 28))
        self.dir_text.setObjectName("dir_text")
        self.file_text = QtWidgets.QPlainTextEdit(Dialog)
        self.file_text.setGeometry(QtCore.QRect(460, 20, 200, 28))
        self.file_text.setObjectName("file_text")
        self.select_dir_btn = QtWidgets.QPushButton(Dialog)
        self.select_dir_btn.setGeometry(QtCore.QRect(10, 20, 90, 28))
        self.select_dir_btn.setIconSize(QtCore.QSize(16, 16))
        self.select_dir_btn.setCheckable(False)
        self.select_dir_btn.setChecked(False)
        self.select_dir_btn.setFlat(True)
        self.select_dir_btn.setObjectName("select_dir_btn")
        self.select_file_btn = QtWidgets.QPushButton(Dialog)
        self.select_file_btn.setGeometry(QtCore.QRect(380, 20, 75, 28))
        self.select_file_btn.setFlat(True)
        self.select_file_btn.setObjectName("select_file_btn")

        self.retranslateUi(Dialog)
        self.search_btn.clicked.connect(Dialog.search_file)
        self.select_dir_btn.clicked.connect(Dialog.select_dir)
        self.select_file_btn.clicked.connect(Dialog.select_file)
        self.file_table.cellClicked['int', 'int'].connect(Dialog.delete_file)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "文件擦除工具"))
        self.search_btn.setText(_translate("Dialog", "搜索"))
        item = self.file_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件路径"))
        self.file_lst_label.setText(_translate("Dialog", "文件列表"))
        self.select_dir_btn.setText(_translate("Dialog", "文件路径："))
        self.select_file_btn.setText(_translate("Dialog", "文件名："))
